/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData location = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData sun_inv = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData sunrise = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData fog_sun = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData fog_moon = const IconData(0xe805, fontFamily: _kFontFam);
}
